/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package keystrokelogin;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.neuroph.core.NeuralNetwork;

/**
 *
 * @author Natan
 */
public class Verification extends javax.swing.JFrame {
    private long timestamp1 = 0;
    private long timestamp2 = 0;
    private ArrayList<Long> time_diff=new ArrayList<Long>();
    private String senhaCorreta;
    /**
     * Creates new form Verfication
     */
    public Verification(String senha) {
        initComponents();
        this.senhaCorreta = senha;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        passwordTextField = new javax.swing.JTextField();
        verificarButton = new javax.swing.JButton();
        avisoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        passwordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextFieldActionPerformed(evt);
            }
        });
        passwordTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordTextFieldKeyReleased(evt);
            }
        });

        verificarButton.setText("Verificar");
        verificarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarButtonActionPerformed(evt);
            }
        });

        avisoLabel.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        avisoLabel.setText("Senha correta");
        avisoLabel.setEnabled(false);
        avisoLabel.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(verificarButton)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(avisoLabel)
                .addGap(94, 94, 94))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(verificarButton)
                .addGap(43, 43, 43)
                .addComponent(avisoLabel)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextFieldActionPerformed
        try {
            verificar();
        } catch (FileNotFoundException ex) {
            System.out.println("FALHA AO ABRIR REDE NEURAL, REDE NEURAL NÃO EXISTE");
            Logger.getLogger(Verification.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_passwordTextFieldActionPerformed

    private void passwordTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTextFieldKeyReleased
        Date date = new Date();
	
        if(evt.getKeyCode()!=java.awt.event.KeyEvent.VK_ENTER){
            avisoLabel.setVisible(false);
            if(timestamp1 == 0) timestamp1 = date.getTime(); 
            else if(timestamp1!=0){
                timestamp2 = date.getTime();         
                long diff = timestamp2  - timestamp1 ;
                time_diff.add(diff);
                System.out.println(diff);
                timestamp1 = timestamp2;
            }
        }
    }//GEN-LAST:event_passwordTextFieldKeyReleased

    private void verificarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarButtonActionPerformed
        try {
            verificar();
        } catch (FileNotFoundException ex) {
            System.out.println("FALHA AO ABRIR REDE NEURAL, REDE NEURAL NÃO EXISTE");
            Logger.getLogger(Verification.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_verificarButtonActionPerformed

    public void verificar() throws FileNotFoundException{
        
        String senhaInserida = passwordTextField.getText();       
        
        if(senhaInserida.equals(senhaCorreta)){
        
            double tempo[] = new double[time_diff.size()];
            for (int i = 0; i < time_diff.size(); i++) {
                tempo[i] = (double)time_diff.get(i);
            }
            
            // load the saved network
            //NeuralNetwork neuralNetwork = NeuralNetwork.load(new FileInputStream(System.getProperty("perceptron.mnet")));
            NeuralNetwork neuralNetwork = NeuralNetwork.createFromFile("perceptron.nnet");
            // set network input
            neuralNetwork.setInput(tempo);
            // calculate network
            neuralNetwork.calculate();
            // get network output
            double[] networkOutput = neuralNetwork.getOutput();
            for (int i = 0; i< networkOutput.length; i++) {
                System.out.println(">> "+networkOutput[i]);    
            }
            if(networkOutput[0] == 1.0){
                avisoLabel.setVisible(true);
                avisoLabel.setText("Senha correta!");
            }
            else {
                avisoLabel.setVisible(true);
                avisoLabel.setText("Senha incorreta!");  
            }
        } else {
            avisoLabel.setVisible(true);
            avisoLabel.setText("Senha incorreta!");
        }
        
        passwordTextField.setText("");
        timestamp1 = 0;
        timestamp2 = 0;
        time_diff = new ArrayList<Long>();        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisoLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JButton verificarButton;
    // End of variables declaration//GEN-END:variables
}
